// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteakholdersMeatup.Data;

#nullable disable

namespace SteakholdersMeatup.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424235531_AddEmailAndOAuthProvider")]
    partial class AddEmailAndOAuthProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SteakholdersMeatup.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeatupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MeatupId", "UserId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeatupId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SplitAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TaxIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipPercent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeatupId")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Meatup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Meatups");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CutName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MeatupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeightOz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeatupId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BillId", "UserId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonenessRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlavorRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<int>("TendernessRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValueRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("AuthProvider", "ProviderUserId")
                        .IsUnique()
                        .HasFilter("[ProviderUserId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Attendance", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Meatup", "Meatup")
                        .WithMany("Attendances")
                        .HasForeignKey("MeatupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meatup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Bill", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Meatup", "Meatup")
                        .WithOne("Bill")
                        .HasForeignKey("SteakholdersMeatup.Models.Bill", "MeatupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meatup");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Meatup", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", null)
                        .WithMany("CreatedMeatups")
                        .HasForeignKey("UserId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Order", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Meatup", "Meatup")
                        .WithMany("Orders")
                        .HasForeignKey("MeatupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meatup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Payment", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Review", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("SteakholdersMeatup.Models.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Meatup", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Bill");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Order", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CreatedMeatups");

                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
