// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteakholdersMeatup.Data;

#nullable disable

namespace SteakholdersMeatup.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425194536_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SteakholdersMeatup.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeatupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MeatupId", "UserId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeatupId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SplitAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TaxIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipPercent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeatupId")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<int>("LeaderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("LeaderUserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.GroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Meatup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueCountry")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VenueLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("VenueLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("VenueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueState")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueStreet1")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueZip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Meatups");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CutName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MeatupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeightOz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeatupId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BillId", "UserId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalPlaceId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.RestaurantSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantName")
                        .IsUnique();

                    b.ToTable("RestaurantSummaries");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbianceRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodQualityRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ServiceRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasteRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.ReviewPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewPhotos");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("AuthProvider", "ProviderUserId")
                        .IsUnique()
                        .HasFilter("[ProviderUserId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Attendance", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Meatup", "Meatup")
                        .WithMany("Attendances")
                        .HasForeignKey("MeatupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meatup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Bill", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Meatup", "Meatup")
                        .WithOne("Bill")
                        .HasForeignKey("SteakholdersMeatup.Models.Bill", "MeatupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meatup");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Group", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.GroupMembership", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Meatup", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.User", "CreatedBy")
                        .WithMany("CreatedMeatups")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.Group", "Group")
                        .WithMany("Meatups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SteakholdersMeatup.Models.Restaurant", "Restaurant")
                        .WithMany("Meatups")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Order", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Meatup", "Meatup")
                        .WithMany("Orders")
                        .HasForeignKey("MeatupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meatup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Payment", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteakholdersMeatup.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Restaurant", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Review", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("SteakholdersMeatup.Models.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.ReviewPhoto", b =>
                {
                    b.HasOne("SteakholdersMeatup.Models.Review", "Review")
                        .WithMany("Photos")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Group", b =>
                {
                    b.Navigation("Meatups");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Meatup", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Bill");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Order", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Restaurant", b =>
                {
                    b.Navigation("Meatups");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.Review", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("SteakholdersMeatup.Models.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CreatedMeatups");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
