import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Sparkles, Star } from 'lucide-react';
import { getPublicRestaurant, generateRestaurantSummary } from '../api/public';
import { useAuth } from '../context/AuthContext';

function StarRow({ label, value }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '6px 0' }}>
      <span style={{ fontFamily: 'var(--font-body)', fontSize: 14, fontStyle: 'italic', color: 'var(--color-text-dim)' }}>
        {label}
      </span>
      <div style={{ display: 'flex', gap: 2 }}>
        {[1,2,3,4,5].map(n => (
          <Star
            key={n}
            size={11}
            fill={n <= value ? 'var(--color-gold)' : 'transparent'}
            stroke={n <= value ? 'var(--color-gold)' : 'rgba(201,166,120,0.25)'}
          />
        ))}
      </div>
    </div>
  );
}

export default function RestaurantDetailScreen() {
  const { name } = useParams();
  const navigate  = useNavigate();
  const { user }  = useAuth();

  const [detail, setDetail]           = useState(null);
  const [loading, setLoading]         = useState(true);
  const [genLoading, setGenLoading]   = useState(false);
  const [genError, setGenError]       = useState('');
  const [expanded, setExpanded]       = useState(null);

  const decodedName = decodeURIComponent(name);

  useEffect(() => {
    getPublicRestaurant(decodedName)
      .then(setDetail)
      .catch(() => setDetail(null))
      .finally(() => setLoading(false));
  }, [decodedName]);

  const handleGenerateSummary = async () => {
    setGenLoading(true);
    setGenError('');
    try {
      const { summary } = await generateRestaurantSummary(decodedName);
      setDetail(d => ({ ...d, aiSummary: summary }));
    } catch (err) {
      setGenError(err.status === 503
        ? 'AI summary requires an Anthropic API key to be configured on the server.'
        : 'Summary generation failed. Please try again.');
    } finally {
      setGenLoading(false);
    }
  };

  if (loading) {
    return (
      <>
        <div className="screen-header">
          <button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={14} /> Back</button>
          <div className="skeleton" style={{ height: 28, width: '60%', marginTop: 8, borderRadius: 6 }} />
        </div>
        <div style={{ padding: '0 24px', display: 'flex', flexDirection: 'column', gap: 12, marginTop: 12 }}>
          {[0,1,2].map(i => <div key={i} className="skeleton" style={{ height: 80, borderRadius: 14 }} />)}
        </div>
      </>
    );
  }

  if (!detail) {
    return (
      <>
        <div className="screen-header">
          <button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={14} /> Back</button>
        </div>
        <div className="empty-state">
          <div className="empty-state-title">Restaurant not found</div>
          <div className="empty-state-sub">No meatups have been recorded here yet.</div>
        </div>
      </>
    );
  }

  return (
    <>
      <div className="screen-header">
        <button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={14} /> Back</button>
        <div className="greeting" style={{ fontSize: 24, marginTop: 8 }}>{detail.name}</div>
        {detail.location && <div className="subgreet">{detail.location}</div>}

        {/* Aggregate stats strip */}
        <div style={{ display: 'flex', gap: 20, marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--color-border)' }}>
          {detail.avgScore != null && (
            <div style={{ textAlign: 'center' }}>
              <div className="stat-num" style={{ fontSize: 28 }}>{detail.avgScore.toFixed(1)}</div>
              <div className="stat-label">Avg Score</div>
            </div>
          )}
          <div style={{ textAlign: 'center' }}>
            <div className="stat-num" style={{ fontSize: 28 }}>{detail.visitCount}</div>
            <div className="stat-label">{detail.visitCount === 1 ? 'Visit' : 'Visits'}</div>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div className="stat-num" style={{ fontSize: 28 }}>{detail.reviews.length}</div>
            <div className="stat-label">{detail.reviews.length === 1 ? 'Review' : 'Reviews'}</div>
          </div>
        </div>
      </div>

      {/* AI Summary */}
      <div className="section-label">AI Summary</div>
      <div style={{ padding: '0 24px 8px' }}>
        {detail.aiSummary ? (
          <div className="ai-summary-box">
            <div className="ai-summary-badge"><Sparkles size={11} /> Generated by Claude</div>
            <p className="ai-summary-text">{detail.aiSummary}</p>
            <button
              className="ai-regen-btn"
              onClick={handleGenerateSummary}
              disabled={genLoading}
            >
              {genLoading ? 'Regenerating…' : '↻ Regenerate'}
            </button>
          </div>
        ) : (
          <div className="ai-summary-box ai-summary-empty">
            <Sparkles size={20} style={{ color: 'var(--color-gold)', marginBottom: 8 }} />
            <p style={{ fontFamily: 'var(--font-body)', fontStyle: 'italic', color: 'var(--color-text-dim)', marginBottom: 14, fontSize: 15 }}>
              No summary yet. Generate one from all reviews for this restaurant.
            </p>
            {genError && <div className="error-msg" style={{ marginBottom: 10 }}>{genError}</div>}
            <button className="submit-btn" onClick={handleGenerateSummary} disabled={genLoading}>
              {genLoading ? 'Generating…' : 'Generate AI Summary'}
            </button>
          </div>
        )}
        {genError && detail.aiSummary && (
          <div className="error-msg" style={{ marginTop: 8 }}>{genError}</div>
        )}
      </div>

      {/* Reviews */}
      <div className="section-label">Reviews ({detail.reviews.length})</div>
      {detail.reviews.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-sub">No reviews yet for this restaurant.</div>
        </div>
      ) : detail.reviews.map(r => (
        <div key={r.id} className="restaurant-review-item">
          {/* Photo strip */}
          {r.photoUrls?.length > 0 && (
            <div className="review-photo-strip">
              {r.photoUrls.map((url, i) => (
                <img key={i} src={url} alt={`Photo ${i + 1}`} className="review-photo-thumb" />
              ))}
            </div>
          )}

          <div
            className="review-item"
            style={{ cursor: 'pointer', borderBottom: 'none' }}
            onClick={() => setExpanded(expanded === r.id ? null : r.id)}
          >
            <div className="review-thumb">
              {r.photoUrls?.length > 0
                ? <img src={r.photoUrls[0]} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                : <div className="marbling" />
              }
            </div>
            <div className="review-content">
              <div className="review-title">{r.cutName}</div>
              <div className="review-meta">
                {r.weightOz ? `${r.weightOz} OZ` : ''}{r.temperature ? ` · ${r.temperature}` : ''}
              </div>
              {r.notes && <div className="review-desc">{r.notes}</div>}
            </div>
            <div className="score-num">{r.overallScore.toFixed(1)}<span>/5</span></div>
          </div>

          {/* Expanded detail */}
          {expanded === r.id && (
            <div className="review-expanded">
              <StarRow label="Service" value={r.serviceRating} />
              <StarRow label="Ambiance" value={r.ambianceRating} />
              <StarRow label="Food Quality" value={r.foodQualityRating} />
              <StarRow label="Taste" value={r.tasteRating} />
              <div style={{ marginTop: 6, fontFamily: 'var(--font-mono)', fontSize: 9, color: 'var(--color-gold-dim)', letterSpacing: '0.15em' }}>
                {new Date(r.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }).toUpperCase()}
              </div>
            </div>
          )}

          <div style={{ height: 1, background: 'var(--color-border-dim)', margin: '0 24px' }} />
        </div>
      ))}
    </>
  );
}
